### ISSUE TITLE
Centralizar os Meetups

### ISSUE THREAD

**Issue by ravanscafi** [awesome-br/awesome-br.github.io#10]
Existem vários grupos dev de [Meetups](meetup.com) no Brasil, por que não centralizá-los aqui também? :wink:

**Comment by vinicius73** [comment]
acho válido, mas nao sei se o formato atual suportaria isso.
Talvez com alguns ajustes.

**Comment by danielschmitz** [comment]
Fale mais sobre esses meetups para avaliarmos ok.

**Comment by danielschmitz** [comment]
@op sumiu :)
