### ISSUE TITLE
Categoria Linux?

### ISSUE THREAD

**Issue by rafa-acioly** [awesome-br/awesome-br.github.io#103]
Tenho algumas apostilas e tutoriais de como trabalhar com linux (desenvolvedores) e pensei que poderia ser criada essa categoria, o que acham?

**Comment by danielschmitz** [comment]
Show de bola! Pode fazer o PR, sabe como proceder?

**Comment by natanaelphp** [comment]
Sou a favor :+1:

**Comment by danielschmitz** [comment]
a categoria foi criada
