### ISSUE TITLE
Categoria expressão regular

### ISSUE THREAD

**Issue by theuves** [awesome-br/awesome-br.github.io#107]
Seria interessante uma categoria para [Expressões Regulares](https://pt.wikipedia.org/wiki/Express%C3%A3o_regular).

**Comment by danielschmitz** [comment]
Olá,

você tem algum link/artigo/video aí nos seus favoritos sobre o tema?

Se sim, por favor faça o PR criando o arquivo sections/regex.json para que possamos iniciar a categoria.

**Comment by danielschmitz** [comment]
Done!
