### ISSUE TITLE
Tags parecidas

### ISSUE THREAD

**Issue by ftonato** [awesome-br/awesome-br.github.io#109]
Estava navegando quando percebi isso que existem tags "parecidas" e me perguntei sobre a necessidade delas, um exemplo simples abaixo:

![plugin-or-plugins](https://cloud.githubusercontent.com/assets/5417662/11635622/278ba588-9cff-11e5-877d-fcbd969cf637.png)
Após acessar a categoria `sublime (editor)`, fui verificar quais as tags existiam, e percebi que existe uma tag chamada **plugin** e outra chamada **plugins**.

Penso que no fim das contas ambas podem se tornar uma única, o mesmo pode acontecer p/ todas as próximas, basta definir um padrão, a minha dica é usar sempre o plural pois quando for pesquisado pelo singular (já contém o prefixo da palavra _na maioria das vezes_), exemplos:

`dica` **→** `dicas`
`filtro` **→** `filtros`

**Comment by vinicius73** [comment]
Como o processo é manual, essa correção também precisa :cry: 
Assim que possível daremos uma atenção, porém se você conseguir resolver seria ótimo :stuck_out_tongue_winking_eye:

**Comment by ftonato** [comment]
Compreendo que o processo seja manual, mas poderíamos adicionar essa _"sugestão"_ [aqui](https://github.com/awesome-br/awesome-br.github.io#como-participar) e dar uma atenção extra na hora de aceitar o(s) **pr**.
Assim que sobrar um tempo, e aproveitando que temos "pouco" material, vou alterar tudo manualmente mesmo.
Se mais algum quiser colaborar, por favor, enviei seus pull requests :+1:

**Comment by danielschmitz** [comment]
Vou alterar algumas coisas aqui. Existem algumas situações que temos que discutir, como por exemplo manter "video" e "screencast". Pra mim é tudo igual, mas preciso de mais opiniões. 

Mesma coisa cmo "guia" e "tutorial", "artigo"

vou tirar o help wanted pq estou atualizando as tags

**Comment by ftonato** [comment]
Entendo que como tudo é **individual** deveria ser tudo no singular, mas daí voltamos p/ aquela parte onde eu digo:

> _a minha dica é usar sempre o plural pois quando for pesquisado pelo singular (já contém o prefixo da palavra na maioria das vezes)_

Seguindo a lógica, se ele entrar e pesquisar por `artigos` não aparecerá nenhum conteúdo pois a tag é `artigo`, do contrário, se todas forem cadastradas no plural, quando ele pesquisar pelo singular ele irá encontrar :)

Claro que esse é meu ponto de vista, mas sejamos democratas :+1:

**Comment by Rodrigo54** [comment]
:+1:  para a dica do @ftonato

**Comment by danielschmitz** [comment]
Concordo, depois que alterar tudo eu faço um replace :)

é muito trabalho, vou fazendo aos poucos

**Comment by ftonato** [comment]
Pode-se fazer por arquivos separados (manualmente), cada membro que quiser colaborar, escolhe um arquivo e faz.
Também acho válido colocar link dessa issue na descrição ou deixar lá a dica de colocar as tags no plural _evitando_ assim **novos erros**!

**Comment by danielschmitz** [comment]
Então, eu penso em usar o travis para checar o tipo de link em uma lista de itens previamente cadastrados. Só preciso de tempo pra fazer isso :) 

e claro, preciso aprender a usar o travis hehe

**Comment by ftonato** [comment]
Beleza, assim que decidir a melhor forma p/ fazer isso avise-nos :)

**Comment by danielschmitz** [comment]
Alterações feitas.

**Comment by danielschmitz** [comment]
Para fins de consulta, hoje na c93ffe99373e3917579752f135f02206a752a544 criei a verificação de tipos de links, para que não sejam criados tipos semelhantes como "video" e videos".
