### ISSUE TITLE
Atualizar a imagem do projeto no README

### ISSUE THREAD

**Issue by ftonato** [awesome-br/awesome-br.github.io#110]
Estava olhando a imagem e percebi que ela é um pouco "antiga" com alguns elementos diferentes da página atual.
Seria uma opção válida atualizar ela?

![Nova imagem](https://cloud.githubusercontent.com/assets/5417662/11636043/35141db4-9d01-11e5-9c20-f8beb07a867c.png)
Acima há uma image da versão atual da home do projeto :)

**Comment by danielschmitz** [comment]
Feito.
