### ISSUE TITLE
Adicionar nova categoria - SEO

### ISSUE THREAD

**Issue by gabrielazevedo** [awesome-br/awesome-br.github.io#111]
Poderia adicionar uma categoria com assuntos sobre SEO, seria bastante interessante :)

**Comment by rafa-acioly** [comment]
você tem algum conteudo para iniciar a categoria ?

**Comment by gabrielazevedo** [comment]
Opa, tenho sim.

**Comment by danielschmitz** [comment]
Olá Grabriel, 

por favor faça o PR de sections/seo.json

Use o sections/base.json como modelo.

Obrigado.

**Comment by gabrielazevedo** [comment]
Pode deixar Daniel, vou fazer o PR.

**Comment by vinicius73** [comment]
ping @gabrielazevedo

**Comment by danielschmitz** [comment]
fechando por inatividade
