### ISSUE TITLE
Criar uma Wiki

### ISSUE THREAD

**Issue by ftonato** [awesome-br/awesome-br.github.io#118]
Alguém já pensou em separar todo conteúdo que hoje está no README.md usando a Wiki do repositório?
Poderíamos deixar no README apenas a descrição do projeto e adicionar nos títulos os links cada "tópico" da Wiki?

Lembre-se que **Wiki**

> Wikis provide a place in your repository to lay out the roadmap of your project, show the current status, and document software better, together.

**Comment by vinicius73** [comment]
Não tenho mt conhecimento com wikis, mas se alguém de propuser a organizar essa informação é bem vindo :wink:

**Comment by ftonato** [comment]
Eu posso ajudar se quiser :)
O que vocês @danielschmitz @jansenfelipe acham?

**Comment by danielschmitz** [comment]
Olá,
mas porque teríamos uma wiki com 2 tópicos ? fiquei confuso :)

**Comment by ftonato** [comment]
Apenas p/ melhor organizar o conteúdo.
Confeso que não "gosto" de README com muito conteúdo, quando ele apenas poderia/deveria resumir o projeto, mas eu na verdade pensava no "futuro".
Veja exemplo do que a Wiki teria/terá:
- Como funciona
- Como participar
- Como testar o projeto no seu computador
  - **Como usar a CLI #70**

A última ainda é uma proposta pois nem está pronto, mas enfim, é apenas uma ideia, sem problemas se a proposta for recusada :)

**Comment by danielschmitz** [comment]
Ah, entendi agora. 

Acredito que será útil quando tivermos mais conteúdo, beleza?

**Comment by ftonato** [comment]
Por mim tudo certo :zap:
