### ISSUE TITLE
Nova categoria - atom 

### ISSUE THREAD

**Issue by jonatasleon** [awesome-br/awesome-br.github.io#124]
Seria interessante criar uma nova categoria para o editor de texto atom, com dicas sobre packages, themes, como usar...

**Comment by natanaelphp** [comment]
Opa! Atom muito me interessa! rs :+1: 

Se já tiver algum link, já faz o pull request.

**Comment by rafa-acioly** [comment]
Já usei mas não consegui me acostumar utilizando o PHP mas tenho muito interesse em saber mais sobre ele.

**Comment by danielschmitz** [comment]
Olá,

por favor faça o PR de sections/atom.json

Use o sections/base.json como modelo.

Obrigado.

**Comment by jonatasleon** [comment]
Blz, estarei fazendo PR.
