### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by allangrds** [awesome-br/awesome-br.github.io#13]
Tenho um lista de links e artigos para design tbm.

**Comment by vinicius73** [comment]
Pode mostrar ela @allanbobs ?

**Comment by allanbobs** [comment]
http://www.colourlovers.com/
http://chiefofdesign.com.br/5-formas-interessantes-de-causar-um-impacto-visual-atraves-da-tipografia/
http://chiefofdesign.com.br/guia-tipografia-parte-01/
http://chiefofdesign.com.br/guia-tipografia-parte-02/
http://chiefofdesign.com.br/guia-tipografia-parte-03/
http://chiefofdesign.com.br/5-formas-interessantes-de-causar-um-impacto-visual-atraves-da-tipografia/

E tenho mais alguns aqui. Não coloquei todos pois salvo os links pelo GetPocket.

**Comment by vinicius73** [comment]
@allanbobs pode mandar uma PR com essa links?

**Comment by allangrds** [comment]
Peço desculpas se pareci impaciente por não ter passado os links. Abaixo segue todos os links que coloquei na tag "design" do meu getpocket. Abaixo não estão links relacionados a UX.

http://colorhunt.co/
http://arquiteturadeinformacao.com/usabilidade/o-que-e-o-sus-system-usability-scale-e-como-usa-lo-em-seu-site/
http://chiefofdesign.com.br/guia-tipografia-parte-01/
http://www.colourlovers.com/
http://imasters.com.br/design-ux/banco-de-imagens-gratis-conheca-10-alternativas-incriveis/?trace=1519021197&source=home
http://www.designculture.com.br/banco-de-imagens-voce-tem-o-seu/
http://www.designculture.com.br/4-dicas-para-ganhar-um-dinheiro-extra-no-fim-do-mes/
http://studio.uxpin.com/ebooks/web-ui-design-best-practices/
http://sobrecapas.blogspot.com.br/2013/11/1356.html
https://blog.fotolia.com/br/2015/04/16/retoque-de-retratos-usando-separacao-de-frequencias/
http://imasters.com.br/design-ux/5-dicas-para-voce-melhorar-os-mockups-e-os-prototipos-de-seu-site/?trace=1519021197&source=home
http://www.designculture.com.br/17-sites-que-todo-designer-precisa-conhecer/
http://blog.wedologos.com.br/freelancer-50-recursos-essenciais-para-designers/
http://fontflame.com/
http://designmodo.com/three-tone-icons/
http://imasters.com.br/design-ux/34-colecoes-de-icones-para-designers-e-devs/?trace=1519021197&source=home
http://chiefofdesign.com.br/15-melhores-blogs-sobre-design/
http://www.des1gnon.com/2014/02/50-recursos-de-referencias-essenciais-para-designers/http://imasters.com.br/design-ux/uma-lista-especial-de-ferramentas-servicos-e-recursos-para-designers/?trace=1519021197&source
http://reallygoodemails.com/
http://imasters.com.br/design-ux/10-ferramentas-uteis-para-design-na-web/?trace=1519021197&source=home

**Comment by danielschmitz** [comment]
@vinicius73 sabe me dizer se estes links já foram inseridos?

**Comment by vinicius73** [comment]
não foram @danielschmitz

**Comment by welksonramos** [comment]
Existem links quebrados e outros conteúdos estão em inglês

**Comment by danielschmitz** [comment]
Eu vou seguir o fluxo padrão do projeto então. 

Para enviar os links, usem PR.

**Comment by allangrds** [comment]
@danielschmitz A categoria foi criada pelo menos ?

**Comment by vinicius73** [comment]
só criar um arquivo em sections que agente já cria a categoria @allanbobs
