### ISSUE TITLE
Google Analytics Tracking Page

### ISSUE THREAD

**Issue by caueops** [awesome-br/awesome-br.github.io#132]
Reparei que não possui nenhum evento para o  `Google Analytics` enviar um tracking em qual página você está.

Quando você navega pelas categorias e rotas diferentes o relatório sempre irá contabilizar `pageview` para a `/`, ou seja, pra home.

Vocês não achariam que seria legal ter essa informação? Poderíamos ter uma série de métricas interessantes :)

**Comment by danielschmitz** [comment]
Seria uma ótima métrica, só não sei como fazer.

**Comment by caueops** [comment]
@danielschmitz Eu posso fazer :)

**Comment by danielschmitz** [comment]
Muito obrigado !
