### ISSUE TITLE
Conteudo pago?

### ISSUE THREAD

**Issue by rafa-acioly** [awesome-br/awesome-br.github.io#138]
A pouco tempo um outro usuario/contribuidor postou um link com conteudo pago, isso é permitido? Creio que seja melhor deixar apenas conteudos gratuitos, o que acham?

O link que me referi é este: https://github.com/awesome-br/awesome-br.github.io/pull/137

**Comment by vinicius73** [comment]
É uma boa questão, não sou contra conteúdo pago. 
Mas seria bom isso ser claro.

**Comment by ftonato** [comment]
Ainda que meu ponto de vista seja irrelevante, é o que penso: https://nandovieira.com.br/desabafo-sobre-compartilhamento-de-arquivos

**Comment by Rodrigo54** [comment]
Não quero defender ninguém, mais só para constar, já existia conteúdo pago no projeto antes desse PR #137 estou falando dos livros [AngularJS na prática](https://github.com/awesome-br/awesome-br.github.io/blob/master/sections/angular.json#L3), [Laravel + AngularJS](https://github.com/awesome-br/awesome-br.github.io/blob/master/sections/laravel.json#L330) e [Php e Laravel Crie aplicações web como um verdadeiro artesão](https://github.com/awesome-br/awesome-br.github.io/blob/master/sections/laravel.json#L798) . A minha opinião é que o foco do projeto sejam os **conteúdos grátis** e _open sorce_.

**Comment by danielschmitz** [comment]
Não vejo problema em ter conteúdo pago.

Seguindo a proposta do awesome-br:

> Nossa proposta é fortalecer a difusão das tecnologias de desenvolvimento web na língua portuguesa.

O único requisito é ter o site em português.

**Comment by ftonato** [comment]
@danielschmitz a proposta é essa, mas existe algo chamado **Direitos de Uso e de Distribuição**, penso que isso deveria deveria ser levado em consideração.

**Comment by rafa-acioly** [comment]
A proposta do repositório é realmente clara mas estou pensando mais pra frente onde pessoas irão querer mandar PR's só para "divulgar" os trabalhos (pagos), eu acredito que seria viável apenas conteúdo grátis, até porque se o usuário/cliente quiser pagar por alguma coisa ele vai direto no google e pesquisa por "comprar".

**Comment by danielschmitz** [comment]
@rafa-acioly  O que você acha de colocar um ícone de que o conteúdo é pago? tipo esse 
http://fortawesome.github.io/Font-Awesome/icon/money/

**Comment by jansenfelipe** [comment]
Boa ideia @danielschmitz !
:+1:

**Comment by rafa-acioly** [comment]
Excelente ideia @danielschmitz, poderia ser criado uma categoria para pagos tambem, mas acho que o icone fica mais elegante. :+1:

**Comment by dlimars** [comment]
Não sou a favor de conteúdo pago tbm, se levar em conta a proposta:

> Awesome BR possui um formato aberto a comunidade que deseja compartilhar conteúdo de qualidade frente às tecnologias mais atuais do mercado.

se algo é pago, então não é aberto.

**Comment by danielschmitz** [comment]
O "aberto a comunidade" diz que qualquer pessoa possa contribui :) 

o formato é aberto, o conteúdo pode ser aberto ou pago. 

Já abri um branch aqui para implementar o ícone, e para implementar um checkbox "Não quero ver conteúdo pago". A pessoa decide o que é melhor para ela. Em breve mando um push

**Comment by dlimars** [comment]
:+1:

**Comment by danielschmitz** [comment]
Fiz um pequeno esboço aqui de como ficaria.

O ícone apareceria quando existisse uma tag "pago". Quem tiver um nome de tag melhor fala aí.

A implementação ta no outro branch lá, quem quiser fazer o checkout e dar uma olhada fiquem a vontade.

@vinicius73  dá uma olhada na implementação que fiz lá. 45ce934d21615c3b1069999dd800112895c2cd27

![2015-12-17 11_05_37-fotos](https://cloud.githubusercontent.com/assets/1509692/11870366/36b2546a-a4ae-11e5-910f-0cebe1bb5512.png)

**Comment by Rodrigo54** [comment]
Acho que permitir conteúdos como o do PR #137 pode acarretar uma avalanche de PR de conteúdos pagos de pessoas que assim como o autor do PR citado criam uma conta no github só com esse propósito. É melhor ter uma **curadoria para os conteúdos pagos**, por exemplo, antes de adicionar um conteúdo pago, é aberto um issue para que ocorra uma votação, se a maioria aprovar o conteúdo só então é feito o merge do conteúdo. Essa é apenas uma ideia que eu tive :grin:  ! O que não pode acontecer é o awesome-br deixar de ser um lugar awesome para ser um lugar cheio de links inúteis. Cabe a nós impedir essa tragédia kkkk

**Comment by danielschmitz** [comment]
Sim, cabe a todos nós fiscalizar. Se existe algum link que seja pago e não tenha qualidade, iremos remover.  O que não podemos fazer é associar o fato do curso/livro/palestra ser ruim somente porque é pago. Isso não é legal.

**Comment by vinicius73** [comment]
@danielschmitz farei um ajuste com essa ideia, to fazendo um fork do seu branch

**Comment by danielschmitz** [comment]
@Rodrigo54 Sobre a equipe que define o conteúdo pago, como isso seria feito? Acho que definirmos umas 5 pessoas para "julgar" o link não seria muito saudável em relação ao trabalho necessário para publicar cada link. Imagine em um dia ter 5 PRs sobre isso e termos que discutir (abrir issue) sobre cada um deles.

Também não desejo que o awesome-br seja um classificados, até então confio que as pessoas não vão ficar publicando links de cursos em excesso. Mas isso pode acontecer.

Resumindo nós temos aqui três caminhos

1- Liberar o conteúdo pago com o ícone e um filtro 
2- Proibir qualquer tipo de conteúdo pago ou que demande cadastro de email, incluindo livros/artigos/videos/cursos
3- Analisar cada link em separado.

**Comment by vinicius73** [comment]
Acredito em uma comunidade auto gerenciável.
A medida que a coisa evolui esse tipo de coisa cai sozinho.

**Comment by danielschmitz** [comment]
Outra ideia:
- Se um curso/video/livro/aula/\* é fornecido por uma EMPRESA ele será BARRADO, pois caracteriza propaganda.
- Se um curso/video/livro/aula/\* é fornecido por uma PESSOA ele será PERMITIDO

O que vocês acham?

**Comment by vinicius73** [comment]
![captura de tela 2015-12-17 as 12 14 54](https://cloud.githubusercontent.com/assets/1561347/11871610/e07c58a2-a4b7-11e5-986e-f8ef3ff81153.png)
![captura de tela 2015-12-17 as 12 15 45](https://cloud.githubusercontent.com/assets/1561347/11871630/f5f38b06-a4b7-11e5-92cc-ec84570edae8.png)

Vou adicionar um filtro global agora

**Comment by danielschmitz** [comment]
Ótimo, ficou só 100% melhor haha

**Comment by vinicius73** [comment]
![captura de tela 2015-12-17 as 12 54 36](https://cloud.githubusercontent.com/assets/1561347/11872612/65b5d7d2-a4bd-11e5-9aba-c55347528c05.png)

Feito

**Comment by vinicius73** [comment]
Agora peço a ajuda de vcs.
9a6f0733d66e40c63faa0326ffaa727ac2af90c8
Identifiquem conteúdo pago e apenas coloquem `paid: true,` que ele será destacado e filtrado.

**Comment by emtudo** [comment]
Acredito que os pontos que gostaria de tratar já foram tratados aqui.
1 - Usuário criou uma conta no git só para adicionar o conteúdo. (um tanto estranho).
2 - Quando se aprova um conteúdo pago, você está aprovando ele dizendo que é bom, ai o cara compra e é ruim, fica feio.
3 - Concordo com os desenvolvedores tem que comer, e concordo que temos que pagar, gostei da ideia de dizer que o conteúdo é pago, mas poderia ter uma advertência nos isentando de responsabilidades juridicamente, não sei como seria isso, só a ideia.

**Comment by ftonato** [comment]
@emtudo até onde eu conheço de legislação o seu terceiro tópico não existe, vamos a um exemplo:

Comprei um livro, e não tenho direito de redistribuir, mas fiz isso e aí uma terceira pessoas faz a mesma coisa que eu fiz.
Quem está errado judicialmente: Eu e a terceira pessoa, pois é "obrigação" de cada um saber se aquilo que distribui tem direitos autorais ou não!

_Novamente, esse é apenas meu ponto de vista!_

**Comment by Rodrigo54** [comment]
A ideia que eu tive era fazer algo semelhante ao que e feito no repositório do [FontAwesome](https://github.com/FortAwesome/Font-Awesome/issues) onde são criados issues para a inclusão de novos ícones. **Qualquer um vai poder criar a issue e todo mundo vai poder votar**

**Comment by danielschmitz** [comment]
Pessoal,

ficou decidido então que os conteúdos pagos terão em seu JSON a entrada `paid: true`, assim temos um meio termo, o que é melhor do que liberar geral ou proibir os links.

@vinicius73 tem um bugzinho lá no checkbox do free, quando seleciona e "deseleciona", dá uma olhada no de angular pra vc ver.

@Rodrigo54 estamos de olho nesses links pagos, se aparecer uma avalanche de links pagos tomaremos outro caminho, mas por enquanto quero acreditar que a comunidade em si não vai fazer isso. A ideia da votação tá de pé também, só quero esperar um pouco para verificar se é necessário mesmo. (Vai q nem aparece mais estes links pagos).

@emtudo Realmente uma pessoa que abriu uma conta nova só para enviar o link é um pouco estranho, nosso formato de PR é usado justamente para que desenvolvedores usem o sistema. Por isso não temos um "formulário de cadastro de links". Vamos continuar observando esse comportamento e obrigado por nos ajudar a estabelecer alguns pontos sobre esse problema.

@rafa-acioly Valew por abrir o issue, as discussões foram muito boas! Continue assim :)

Agradeço a todos por terem ajudando, é assim que fazemos uma comunidade melhor.

**Comment by emtudo** [comment]
legal!

**Comment by emtudo** [comment]
@danielschmitz não precisa agradecer, faço parte desse projeto rsrsrs

**Comment by vinicius73** [comment]
Em virtude a definição do assunto estou fechando a issue.
Se mais algum fato sobre isso ocorrer, podemos reabrir ela.
Obrigado por todas as interações.
