### ISSUE TITLE
Adicionar tecnologia ASP NET

### ISSUE THREAD

**Issue by pedrofernandesfilho** [awesome-br/awesome-br.github.io#153]
Seria interessante um tecnologia ASP NET para poder compartilhar links sobre este assunto.

**Comment by vinicius73** [comment]
Pode mandar PR adicionando @pedrofernandesfilho :)

**Comment by vinicius73** [comment]
ping @pedrofernandesfilho

**Comment by pedrofernandesfilho** [comment]
@vinicius73, estive estudando um pouco melhor o Git para poder contribuir. E também estava meio corrido por esses dias. Em breve envio PR. Valeu!
