### ISSUE TITLE
Erro na renderização da filtragem "Free?"

### ISSUE THREAD

**Issue by jonatasleon** [awesome-br/awesome-br.github.io#158]
Constatei a seguinte situação quando se filtra uma listagem, tirei os seguintes prints para que pudessem entender mais claramente
## Antes de filtrar

![antes](https://cloud.githubusercontent.com/assets/7952914/13221607/0748754c-d95b-11e5-8e87-2cbb22ae9bc3.PNG)
## Durante a filtragem

![durante](https://cloud.githubusercontent.com/assets/7952914/13221609/074c5798-d95b-11e5-8bd2-414261df6eeb.PNG)
## Depois que desmarca a filtragem

![depois](https://cloud.githubusercontent.com/assets/7952914/13221608/074afaa6-d95b-11e5-822e-b84bb82f3b45.PNG)

**Comment by vinicius73** [comment]
Obrigado pelo feedback :+1: 
Vamos ver isso em breve!
