### ISSUE TITLE
Adicionar nova categoria - Testes de Softwares

### ISSUE THREAD

**Issue by alissonbovenzo** [awesome-br/awesome-br.github.io#165]
Gostaria de solicitar a inclusão de uma nova categoria, acredito ser importante manter uma seção para  TDD/BDD/etc

**Comment by vinicius73** [comment]
Pode mandar PR adicionando elas e alguns links @alissonbovenzo ?

**Comment by alissonbovenzo** [comment]
Claro! Vou criar agora e ja faço a PR

**Comment by jonatasleon** [comment]
Criar uma seção para testes não poderia causar redundância? Exemplo: Na seção TDD há o link de um vídeo de introdução TDD com Python, mas esse mesmo vídeo entraria na seção Python.

**Comment by leonanluppi** [comment]
Acho que não, uma seção dedicada a teste ou qualquer outro assunto é sempre bom. Separar as responsabilidades.

**Comment by alissonbovenzo** [comment]
Acredito que não pois Testes indiferem-se da linguagem, acredito que um video sobre TDD com Python deveria realmente estar na seção de TDD, mesmo sendo um video usando python, é um video sobre a técnica, utilizando uma linguagem.
Mas entendi o que você quis dizer, esse vídeo poderia entrar nas duas seções, mas como o assunto principal do vídeo é TDD e não Python, deveria entrar na seção Testes .

**Comment by jonatasleon** [comment]
@leonanluppi sempre é bom desde que não entre em conflito com outra seção.

**Comment by jonatasleon** [comment]
@alissonbovenzo é indiferente de linguagem no que se trata ao conceito, mas, por exemplo, a forma prática que se realiza testes unitários em Python já não é a mesma que se faz em Android. O link que você adicionou na seção de testes é um exemplo ideal para estar lá, já que aborda o que são testes de software, e utiliza duas linguagens. Mas um conteúdo sobre Testes de Instrumentação já penso que deva entrar na seção Android por ser muito específico.

**Comment by vinicius73** [comment]
Infelizmente ainda não há uma "convergência" de links. Então os links podem ser "duplicados" em beneficio da divulgação.
Então um link de testes em python pode estar nas duas seções.
