### ISSUE TITLE
Adicionar nova categoria - Desenvolvimento de Games

### ISSUE THREAD

**Issue by victorvoid** [awesome-br/awesome-br.github.io#170]
Iria facilitar demais para quem desenvolve games.

**Comment by jonatasleon** [comment]
No entanto teria que haver outras várias categorias. Ex: Unreal, Corona SDK, Unity

**Comment by vinicius73** [comment]
Todas podem ser agrupadas em "Desenvolvimento de Games"

**Comment by jonatasleon** [comment]
Ai usaria a TAG para indicar qual a tecnologia? Aí fica "Desenvolvimento de Games" como seção e a plataforma (unity, unreal, corona) coloca na tag.

**Comment by danielschmitz** [comment]
Estamos aguardando alguém com links bacanas aí fazer o PR !
