### ISSUE TITLE
Dúvida sobre o autor

### ISSUE THREAD

**Issue by renatosuero** [awesome-br/awesome-br.github.io#173]
Gostaria de criar uma sessão para elixir, o primeiro item que gostaria de adicionar é este http://elixirschool.com/ que foi traduzido, estou em dúvida sobre o autor, coloco o criador ,as pessoas que traduziram(oq é complicado pq teria que ficar caçando os nomes) ou no autor poderia ser algo tipo comunidade?

**Comment by jonatasleon** [comment]
Ao meu ver seria suficiente o nome da comunidade, há outros links aqui que estão assim. 

[Esse por exemplo](https://github.com/awesome-br/awesome-br.github.io/blob/master/sections/css.json#L84):

``` json
{
  "name": "Aprendendo Layout com CSS",
  "url": "http://pt-br.learnlayout.com/",
  "type": "tutorial",
  "tags": [
    "css"
  ],
  "author": {
    "name": "Bocup",
    "url": "https://bocoup.com/"
  }
}
```

**Comment by renatosuero** [comment]
Vou adicionar e mando um PR pra ver como ficou ai resolvemos lá
