### ISSUE TITLE
Item em inglês (seção Vim)

### ISSUE THREAD

**Issue by renatosuero** [awesome-br/awesome-br.github.io#175]
O primeiro item "Dicas Vim" está em inglês

**Comment by vinicius73** [comment]
Estavamos decidindo se permitiriamos ou não conteúdo não `pt-BR`.
Ficou sub-acordado que posts, artigos e videos deveriam ser em pt, projetos, repos e pacotes deveram ser de autoria `BR` esse deve ter sido um dos links que entrou antes desse "acordo".

Fique a vontade de mandar uma PR removendo esse e outros links que se enquadrem na mesma situação.

**Comment by renatosuero** [comment]
Já removido
