### ISSUE TITLE
Adicionar Categoria - Puppet

### ISSUE THREAD

**Issue by FelixCoutinho** [awesome-br/awesome-br.github.io#176]
Conhecimentos relacionados a tecnologias de provisionamento extremamente relevantes. Assim como o Docker, o Puppet é uma tecnologia que exige uma exclusiva.

Puppet - Provisionamento/Virtualização

**Comment by vinicius73** [comment]
Talvez uma caregoria `devops` se encaixe bem. O que acha?

**Comment by FelixCoutinho** [comment]
Pode ser

**Comment by FelixCoutinho** [comment]
+1

**Comment by jonatasleon** [comment]
Pode fazer o PR adicionando a categoria e um link

**Comment by andergtk** [comment]
Já foi adicionado a categoria?

**Comment by jonatasleon** [comment]
@andergtk ainda não

**Comment by andergtk** [comment]
@jonatasleon e vai ser adicionado a categoria DevOps?

**Comment by jonatasleon** [comment]
Isso, você faz o PR adicionando a categoria e algum link

**Comment by jonatasleon** [comment]
@vinicius73 como já foi adicionada a categoria DevOps, pode fechar aqui
