### ISSUE TITLE
domínio awesome-br.com

### ISSUE THREAD

**Issue by danielschmitz** [awesome-br/awesome-br.github.io#18]
O que vocês acham de usarmos esse domínio?

Eu já comprei ele, aí seria apontar ele pro github.

Ao invés de termos  awesome-br.github.io  teríamos awesome-br.com

Se digitar awesome-br.github.io  funciona também :)

**Comment by jansenfelipe** [comment]
:+1:

**Comment by welksonramos** [comment]
:+1:

**Comment by vinicius73** [comment]
:+1:

**Comment by danielschmitz** [comment]
testem por favor
awesome-br.com

**Comment by welksonramos** [comment]
:smile:
