### ISSUE TITLE
Adicionar Categoria - CodeIgniter

### ISSUE THREAD

**Issue by Rodrigo54** [awesome-br/awesome-br.github.io#183]
Esse Framework ta ressurgindo das cinzas feito uma fênix :joy: :joy: :joy: :joy: 
Acho que vai ajudar muita gente.

**Comment by rafa-acioly** [comment]
Ressurgindo porque? alguma novidade nele?

**Comment by vinicius73** [comment]
Desculpe, já usei mt CI e até acompanho o git deles, e não vejo nenhuma novidade.
Nem se tratando de posts e tutoriais a respeito. Não sou contra a categoria, mas ela precisa de justificativa.
Há conteúdo pt-BR disponivel que justifique?

**Comment by Rodrigo54** [comment]
Existe bastante tutoriais principalmente em vídeos que são novos sem falar dos pacotes e tudo mais.

Se existe espaço para categorias com apenas 1 ou 2 links creio que não custaria nada criar mais uma kkkkkkkkkkkkkk

Mais acho que se criarmos essa categoria ganharíamos em audiência e conseguiríamos criar algo parecido a categoria do laravel

Mais é apenas uma sugestão de categoria
