### ISSUE TITLE
Adicionar categoria MongoDB

### ISSUE THREAD

**Issue by GabrielDeveloper** [awesome-br/awesome-br.github.io#187]
Tenho trabalhado a um tempo com esse banco e acredito que vai adicionar muito valor a todos com essa categoria!

Já tenho alguns links que me ajudaram bastante e quero compartilhar para ajudar mais pessoas!

**Comment by renatosuero** [comment]
@GabrielDeveloper acabei de fazer o que quer, mas com a seção elixir, oq fiz foi criar a seção, botar os links e mandar PR e agora ver o que rola.

**Comment by vinicius73** [comment]
se puder fazer o imenso favor de adicionar os link presentes no http://nomadev.com.br/ seria ótimo!

**Comment by GabrielDeveloper** [comment]
Com certeza, lá tem muito conteúdo de primeira!! Já mando o PR!!
