### ISSUE TITLE
Adicionar categoria Xamarin

### ISSUE THREAD

**Issue by jonatasleon** [awesome-br/awesome-br.github.io#198]
Com a compra do Xamarin pela Microsoft e o fato de ter tornado a ferramenta gratuita (até 5 devs) é interessante termos uma seção do mesmo aqui. Não tenho nenhum link em pt-br no momento, ainda estou no começo do aprendizado, mas já fica aí a proposta à quem quiser fazer o PR.

**Comment by danielschmitz** [comment]
feito
