### ISSUE TITLE
Separar Angular entre Angular e Angular 2

### ISSUE THREAD

**Issue by jonatasleon** [awesome-br/awesome-br.github.io#270]
Sendo as duas versões muito distintas entre si, poderia ser legal separar em duas seções

**Comment by vinicius73** [comment]
É algo a se consideram, tendo mais feedbacks podemos separar.

**Comment by danielschmitz** [comment]
Sim, poderia entre AngularJS e Angular 2

Aliás, se permitirem, separo aqui. (só esperando mais feedback)

**Comment by caueops** [comment]
👍  Acho uma boa ideia.

**Comment by jayralencar** [comment]
Também acho uma boa ideia.

**Comment by jonatasleon** [comment]
Parece que todo mundo curtiu, @danielschmitz você separa aí então?

**Comment by danielschmitz** [comment]
Sim! Só sobrar um tempinho

**Comment by danielschmitz** [comment]
removi o  challenge accepted pq vi q tinha o assigned # :)
