### ISSUE TITLE
Página de contribuidores

### ISSUE THREAD

**Issue by jayralencar** [awesome-br/awesome-br.github.io#279]
O que vocês acham da criação de uma página de contribuidores, usando a API do GitHub [https://api.github.com/repos/awesome-br/awesome-br.github.io/contributors](https://api.github.com/repos/awesome-br/awesome-br.github.io/contributors),. Pra dar uma moral pra galera?

**Comment by danielschmitz** [comment]
Acho legal, se alguém quiser montar a página e enviar via PR, fique a vontade que publicamos. O ideal seria manter o design do awesome-br, então talvez o @vinicius73 possa ajudar nisso.

**Comment by vinicius73** [comment]
# Apoiado

**Comment by emtudo** [comment]
Também apoio!

**Comment by murilolopes** [comment]
Qual o status da feature? Alguem trabalhando nela, caso não gostaria de pegar.

**Comment by danielschmitz** [comment]
@murilolopes pode pegar sim :)
Seria interessante continuar usar a identidade visual do projeto, usando as "caixinhas coloridas" com o nome das pessoas. @vinicius73 que biblioteca vc usou mesmo pra fazer essas caixinhas?

**Comment by vinicius73** [comment]
http://btmills.github.io/geopattern/

**Comment by JoaoAntonioMaruti** [comment]
Alguém está fazendo? posso pegar ?

**Comment by vinicius73** [comment]
feito por @JoaoAntonioMaruti #312
