### ISSUE TITLE
Adicionar Tecnologia/Categoria Cakephp

### ISSUE THREAD

**Issue by flavianohonorato** [awesome-br/awesome-br.github.io#283]
Poderia adcionar a categoria Cakephp, talvez eu possa ajudar com alguns links.

**Comment by danielschmitz** [comment]
Olá, nós alteramos a forma como a tecnologia é inserida. Veja: Se você deseja adicionar uma nova tecnologia, edite o arquivo sections.json incluindo um novo item e adicione o relativo arquivo json no diretório sections. Você pode usar o arquivo sections/base.json como base. Não adicione uma categoria vazia. Teste e faça o PR para que possamos adicionar.
