### ISSUE TITLE
JSF

### ISSUE THREAD

**Issue by franckaragao** [awesome-br/awesome-br.github.io#284]
Adicionar JSF como uma nova tecnologia

**Comment by danielschmitz** [comment]
Olá, nós alteramos a forma como a tecnologia é inserida. Veja: Se você deseja adicionar uma nova tecnologia, edite o arquivo sections.json incluindo um novo item e adicione o relativo arquivo json no diretório sections. Você pode usar o arquivo sections/base.json como base. Não adicione uma categoria vazia. Teste e faça o PR para que possamos adicionar.
