### ISSUE TITLE
Dropdown quebrando no grid responsive

### ISSUE THREAD

**Issue by caueops** [awesome-br/awesome-br.github.io#285]
Eu fiz os testes na home do site, utilizando `Iphone 5s` e veja o que acontece com o dropdown:

![img_2205](https://cloud.githubusercontent.com/assets/7065285/15684386/45dafce6-273d-11e6-9213-13c98b4abf9e.PNG)

**Comment by danielschmitz** [comment]
Este dropdown deveria abrir na forma nativa, confirma @vinicius73  ?

**Comment by vinicius73** [comment]
Infelizmente não, ele é um UL da vida @danielschmitz

**Comment by danielschmitz** [comment]
então por enquanto, neste layout, nao tem como....
