### ISSUE TITLE
Adicionar nova categoria - BI (Business intelligence)

### ISSUE THREAD

**Issue by JoaoAntonioMaruti** [awesome-br/awesome-br.github.io#311]
Senhores, recentemente entrei para o mundo de BI, comecei a estudar e encontrei uma grande comunidade brasileira, tenho links úteis em pt-br que me auxiliaram nessa jornada, gostaria de contribuir com a comunidade.

**Comment by robsonfs** [comment]
Fala mestre..

Você mesmo pode criar a categoria e adicionar os links, basta seguir [essas instruções](https://github.com/awesome-br/awesome-br.github.io#como-participar) . Preferir, coloque os links nos comentários que eu adiciono...

**Comment by rafa-acioly** [comment]
Acho valido!

**Comment by danielschmitz** [comment]
@JoaoAntonioMaruti, você pode criar a categoria e fazer m PR. Estaremos aguardando! Mais informações [neste link](https://github.com/awesome-br/awesome-br.github.io#como-participar)
