### ISSUE TITLE
Link de Django estragando o layout

### ISSUE THREAD

**Issue by ygorlazaro** [awesome-br/awesome-br.github.io#326]
![image](https://cloud.githubusercontent.com/assets/14074484/17162180/4907e626-538a-11e6-8dba-6c3577d15c99.png)

O link sobre Django está com muitas labels e descrições, o layout está quebrando.

Resolução 1368 horizontal.

**Comment by rafa-acioly** [comment]
o layout não esta quebrado amigo, acredito que seja assim mesmo.
cada "ficha" não precisa ser exatamente do tamanho das outras.

**Comment by danielschmitz** [comment]
também não vejo problemas. Se houvessem muitas tags em todos os quadrinhos, cada um seria de um tamanho :) tudo bem @ygorlazaro ?

**Comment by ygorlazaro** [comment]
Eu entendo vocês, mas ficou um pouco estranho no meu ponto de vista. Nada que mate, mas... rs

O YII Framework também tem tags, mas todo o restante não. Acho que poderia rolar uma maneira mais padronizada de exibir esse conteúdo. Mas ok, sou programador e não designer ;)

**Comment by danielschmitz** [comment]
Sim, estamos repassando o "core" do awesome pra Vuejs, essas questões serão discutidas. Fique a vontade em nos ajudar! Vou abrir um issue sobre isso logo logo!!

**Comment by ygorlazaro** [comment]
Ah, aí sim. Com certeza estou dentro =D

**Comment by danielschmitz** [comment]
Agora que vi que as tags estavam na section. Como nao é padrão (na verdade nem tinha, sorry), removi pra ficar melhor.
