### ISSUE TITLE
awesome-br.com quebrou na produção 

### ISSUE THREAD

**Issue by Kirmayrtomaz** [awesome-br/awesome-br.github.io#362]
Quando acessei o site hoje, de vários links quebrados.

[![Imagem da tela inicial ](https://s18.postimg.org/68shu3ie1/Captura_de_ecr_de_2016_11_25_14_55_43.png)](https://postimg.org/image/giuwtc89h/)

**Comment by vinicius73** [comment]
Algum problema com o github-pages

**Comment by vinicius73** [comment]
Forcei uma atualização, voltou.
