### ISSUE TITLE
Nova seção: CakePHP

### ISSUE THREAD

**Issue by flavianohonorato** [awesome-br/awesome-br.github.io#371]
Que tal adicionarmos uma seção para o framework CakePHP? tenho alguns links para contribuir.

**Comment by rafa-acioly** [comment]
o conteúdo sera bem vindo.

**Comment by saraiva1989** [comment]
Acho que podem fechar esse problema, pois já foi adicionado

![Captura de Tela 2019-05-02 às 20 42 55](https://user-images.githubusercontent.com/40599423/57113425-e4feec80-6d1a-11e9-9273-e0bd616b1d18.png)
