### ISSUE TITLE
Add mais categorias 

### ISSUE THREAD

**Issue by welksonramos** [awesome-br/awesome-br.github.io#7]
CSS, Ember.js, Grunt, Gulp, Javascript, Nodejs, Slushjs, Yeoman

**Comment by danielschmitz** [comment]
Nesse fim de semana vou dar uma atualizada geral :+1:

**Comment by welksonramos** [comment]
Show de bola o projeto :+1: 

Também poderia adicionar um task runner grunt ou gulp para automatizar  o desenvolvimento  :smile:

**Comment by vinicius73** [comment]
@danielschmitz @welksonramos 
Converti todo o sistema para um SPA, agora nao precisa mais criar um arquivo index.html para cada seção.
Ainda precisa de ajustes, mas acredito que assim facilita todo o processo.

**Comment by danielschmitz** [comment]
ficou AWESOME! hehe

Será que tem como colocar um titulo da tecnologia atual que a pessoa está vendo? Tipo como era o brandcumb (q nao tinha muita lógica hehe). Atualmente eu só consigo saber que estou no PHP se olhar pra url. Isso no mobile não funciona.

Nesse fim de semana vou atualizar a documentação e adicionar mais categorias.

**Comment by welksonramos** [comment]
Muito bom!!!

**Comment by vinicius73** [comment]
Acabei de fazer uns tweaks e bugfix, se der tempo ajusto para conter titles tbm :pray:

**Comment by danielschmitz** [comment]
incluí diversas tecnologias, menos Slushjs e Yeoman que não conheço ainda. Vou dar uma olhada. 

Vou deixar o issue aberto se alguém quiser comentar mais a respeito

**Comment by theuves** [comment]
Seria interessante uma categoria para a linguagem de programação [**Go**](https://pt.wikipedia.org/wiki/Go_%28linguagem_de_programa%C3%A7%C3%A3o%29) (Já que não existe praticamente **nenhum** conteúdo sobre ela, em português).

**Comment by vinicius73** [comment]
acho válido @theuves 
Você tem algum conteúdo ae para já entrar com alguma coisa?

**Comment by theuves** [comment]
**Alguns links:**
- **http://www.golangbr.org/** - Uma versão em português da página oficial.
- **http://go-tour-br.appspot.com/** - Uma introdução interativa para a linguagem.
- **http://goporexemplo.golangbr.org/** - Uma introdução, usando programas de exemplo.
- **http://tutorial.danielmazza.info/go** - Um tutorial.

**Comment by vinicius73** [comment]
@theuves Pode mandar uma PR com os links agora :)
