### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by welksonramos** [awesome-br/awesome-br.github.io#70]
Estou criando uma CLI (em desenvolvimento) para facilitar a inserção de links no projeto...
[awesome-br-cli](https://github.com/welksonramos/awesome-br-cli), ela é baseada no [freetime-cli](https://github.com/free-time/freetime-cli).

Faltam alguns ajustes para ficar totalmente funcional

**Comment by vinicius73** [comment]
Massa!!

**Comment by danielschmitz** [comment]
Muito interessante!!

**Comment by Rodrigo54** [comment]
:+1:

**Comment by danielschmitz** [comment]
Aliás quando terminar, ou se precisar de ajuda, podemos transferir o seu **welksonramos/awesome-br-cli** para **/awesome-br/awesome-br-cli**  

te coloco nesse projeto como admin ok.

**Comment by diegosorrilha** [comment]
Alto padrão! :D

**Comment by welksonramos** [comment]
Opa, show de bola! Estarei dando uma revisada nele hoje à noite,  e acrescentarei um gif no README do projeto  mostrando seu funcionamento. Toda ajuda é bem vinda @danielschmitz  :)

**Comment by welksonramos** [comment]
Pessoal, retomei o desenvolvimento da CLI e aviso que a mesma já está funcional :smile:

**Comment by vinicius73** [comment]
Manda uma PR atualizando nosso README @welksonramos :)

**Comment by welksonramos** [comment]
Pode deixar :+1:

**Comment by vinicius73** [comment]
:+1:
