### ISSUE TITLE
Permitir que os itens sejam adicionados através de formulário web

### ISSUE THREAD

**Issue by teles** [awesome-br/awesome-br.github.io#73]
Adicionar um novo item poderia ficar mais simples.

Criei uma lista awesome pouco tempo atrás https://github.com/teles/awesome-seo

O processo de adicionar novos itens nessa lista é:
- Adicionar o link numa planilha do google drive (essa https://docs.google.com/spreadsheets/d/1QQ0v0XqUQC3p3brUMMZ81aQSwedbbEXs0eTq9k0zTu0/edit?usp=sharing)
-  Rodo um script nodejs que atualiza os arquivos no meu repositório (https://github.com/teles/awesome-seo/blob/master/update.js) 
- Faço um commit e um push 

Se quiserem posso colocar essa opção de atualizar via formulário usando planilha.

**Comment by danielschmitz** [comment]
Olá teles, tudo bem?

primeiramente obrigado pela dica. Devido ao grande número de tecnologias que estão envolvidas no awesome-br, é mais fácil para nós fazer o merge pela própria interface do github. Dessa forma decentralizamos um pouco nossa tarefa de manter tudo em ordem.

**Comment by teles** [comment]
Tudo bem, @danielschmitz.
Então tudo bem, realmente isso iria alterar o processo de trabalho, embora o script node possa ser configurado para gerar os .json da pasta sections. Mas se achar melhor pode fechar essa issue :)
