### ISSUE TITLE
Centralizar os grupos de Slack

### ISSUE THREAD

**Issue by ravanscafi** [awesome-br/awesome-br.github.io#9]
Existem vários grupos dev de Slack no Brasil, por que não centralizá-los aqui também? :wink:

**Comment by vinicius73** [comment]
Acho que se encaixa bem no formato, alem de ser muito útil :+1:

**Comment by jansenfelipe** [comment]
see https://github.com/joselitojunior/slack-list-brazil

**Comment by danielschmitz** [comment]
Se o @joselitojunior (parece ser o owner) concordar, acho válido :+1:

**Comment by renatosuero** [comment]
Seria legal ter um link dentro da categoria :+1:

**Comment by vinicius73** [comment]
Nova lista de slacks https://slackbrazil.github.io/#/
