### ISSUE TITLE
Categoria Livros?

### ISSUE THREAD

**Issue by rafa-acioly** [awesome-br/awesome-br.github.io#99]
Existem varios e-books, pdf's e afins relacionados a diversas linguagens de programação e creio que seria uma boa ideia criar a categoria "Livros / Ebooks"

**Comment by Rodrigo54** [comment]
Mais já existe tag para **`livros`** por onde o usuário pode pesquisar nas categorias

![](http://i65.tinypic.com/2gxdwfl.png)

**Comment by danielschmitz** [comment]
Eu acredito que devemos focar na tecnologia em si, e a partir dela colocar a tag livro.

Mais pra frente o @vinicius73 faz um script que pega a tag livros de todas as tecnologias e faz o reverso :yum: 

Ok @rafa-acioly ?

**Comment by vinicius73** [comment]
justo :yum:

**Comment by rafa-acioly** [comment]
de acordo.
